INSERT  INTO USUARIO (ID, EMAIL, NOME, PASSWORD, USERNAME) 
VALUES (1, 'email@email.com', 'EDUARDO', '$2y$10$SpfHja/.DG7twEBC719/qOWVmSzZk5NLKfq99lvc2/NAH3P2tlMQ2', 'ntidudu');

INSERT INTO USUARIO_FUNCAO VALUES (1, 'ADM');